### ISSUE TITLE
cleanup ntptutorial

### ISSUE THREAD

**Issue by semorrison** [leanprover/reservoir#11]
[Now](https://github.com/wellecks/ntptutorial/pull/1) that ntptutorial doesn't have a `lean_lib`, all the failures on reservoir are spurious, right? Can we discard them?

**Comment by tydeu** [comment]
@semorrison No, they are not. `ntptutorial` is on a very old lean version, so the new version failures are correct. However, ntptutorial was  successfully built today with its version of Lean, so it now has a gold checkmark.
