### ISSUE TITLE
Improve how reservoir shows the build status of Lean 4 projects

### ISSUE THREAD

**Issue by utensil** [leanprover/reservoir#2]
As reported on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/219941-Machine-Learning-for-Theorem-Proving/topic/Making.20more.20training.20data/near/405841232), particularly:

@PatrickMassot:

> Following [the link](https://reservoir.lean-lang.org/packages/leanprover--community-mathematics_in_lean) suggests reservoir complains MIL doesn't build with v4.4.0-rc1, which completely expected for a project whose current toolchain is leanprover/lean4:v4.2.0-rc4. I understand you wish to indicate which repo tracks monthly Lean releases, but I think this big red cross is a bit too much and doesn't convey the relevant message.

> More generally the landing page of reservoir is full of those red crosses and I think this is both unfair and very bad to communicate what is going on with Lean.

@utensil :

> reservoir aims to keep the builds up-to-date, but maybe for the current status, it should compile with the declared toolchain, and if the declared toolchain compiles but not the latest toolchain, it's better to be a green ✅  with an ℹ️  to indicate it's better to be upgraded.

See also [the Lean 3 analogue of reservoir for comparison](https://leanprover-community.github.io/lean3/lean_projects.html).

**Comment by tydeu** [comment]
The addition of the gold-checkmark for successful builds on old toolchains in 5bc2c84 appears to have resolved this issue based on [the follow-up discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Reservoir.20status.20display/near/406983417), so I am closing it.
