### ISSUE TITLE
why repo name is not used?

### ISSUE THREAD

**Issue by Seasawher** [leanprover/reservoir#24]
As I recall, in the past Reservoir used to display repo name of GitHub. But now it seems to use directory name in list title. 

why? I don't understand the merits of this modification. 

thank you.

**Comment by tydeu** [comment]
@Seasawher  Reservoir now uses the package name defined in the Lake configuration file of the package for its name (i.e., the `foo` of a `package foo` statement). This allows packages to have a different name from their repository on GitHub. This is useful, for example, if the repository has prefixes/suffixes indicating it is a Lean repository that don't really belong as part of the package name on the Lena-only Reservoir (e.g., [socket.lean](https://github.com/hargoniX/socket.lean), [lean4-cli](https://github.com/leanprover/lean4-cli)). It also allows package names to support different character sets than what GItHub does  (e.g., have some unicode in them).

This change was made in #18.

**Comment by Seasawher** [comment]
@tydeu 

Thanks for the reply. I see, so it refers to the package name rather than the directory name.
I have understood the benefits of the change.
