### ISSUE TITLE
repo name is outdated

### ISSUE THREAD

**Issue by Seasawher** [leanprover/reservoir#25]
Reservoir page is: https://reservoir.lean-lang.org/@Seasawher/Src

but `lakefile` of the repository contains:

```lean
package «Lean Book» where
  -- add package configuration options here
  leanOptions := #[
    ⟨`autoImplicit, false⟩,
    ⟨`relaxedAutoImplicit, false⟩
  ]
```

(In the past, the package name was Src.)

Why has the package name not been updated and is still in `Src`?

related #24

**Comment by tydeu** [comment]
Oops! This appears to be a bug in website with handling the space in the package name. (It appears you were the first Lean developer to use one!) I am busy this week, so I might not have the time to fix it now, but I will definitely address this by next week.
