### ISSUE TITLE
"how used" section

### ISSUE THREAD

**Issue by Seasawher** [leanprover/reservoir#29]
see #7

The lakefile shows the repositories marked `require`. This can be aggregated to make a list of repositories that use it directly for each repository.

Conversely, it would be possible to list the repositories using each repository. This is an indicator of the impact of the package.

**Comment by tydeu** [comment]
@Seasawher How is this different from #7? It seems like a duplicate.

**Comment by Seasawher** [comment]
I thought #7 was only about 1.

1. what each repository depends on
2. where each repository is used

**Comment by tydeu** [comment]
@Seasawher Ah. It is about both as well.

1. **Dependencies:** What each package depends on.
2. **Dependents:** What packages depend on it (i.e., which packages use it).
