### ISSUE TITLE
RFC: use github repo name

### ISSUE THREAD

**Issue by joneugster** [leanprover/reservoir#34]
Is it a deliberate choice to display `[github user]/[Library name]` instead of `[github user]/[github repo]`  on the tiles?

I think this is slightly confusing and missleading. For example, I think the following should say `leanprover-community/NNG4` somewhere. What would happen if `leanprover-community` had two repos defining a lean-lib called `Game`?

![Screenshot_20240530_002124](https://github.com/leanprover/reservoir/assets/9141564/69b02939-cd66-4bea-8908-344a479d2260)

Maybe `leanprover-community/NNG4 : Game` could be a better title?

(ofc one can argue that all games should just be excluded because they aren't packages in the sense that you would ever require them, but still the question about unique library names stands regardless)

**Comment by tydeu** [comment]
@joneugster It *is* a deliberate choice to use the package name defined in Lake for the package versus the one used on GitHub. As it currently stands, Lake cannot require two packages with the same name, so having two packages by a single owner with the same name would be just as incompatible for Lake as it is for Reservoir.

**Comment by joneugster** [comment]
I see your point, and I guess the NNG (and any other game) should actually be excluded on reservoir anyways because it is supposed to be a fork of https://github.com/hhu-adam/GameSkeleton

(and its just a technical/historic reason that github doesn't realise that)
