### ISSUE TITLE
highlight "intended" toolchain

### ISSUE THREAD

**Issue by semorrison** [leanprover/reservoir#5]
In the right sidebar in individual package pages, e.g. https://reservoir.lean-lang.org/@verified-optimization/CvxLean, we currently show the list of Lean toolchains which we've tried building against.

Can we highlight the "intended" toolchain (i.e. what is currently in the `lean-toolchain` file)? Just putting this toolchain in bold would suffice.

If the "intended" toolchain is not even on the list we could optionally display this information in a line below the list of built toolchains, but this can be a separate request to the highlighting request.

**Comment by tydeu** [comment]
> Can we highlight the "intended" toolchain (i.e. what is currently in the `lean-toolchain` file)? Just putting this toolchain in bold would suffice.

Should the `lean-toolchain` file in question be the one on which the build was tested or the current toolchain in master? That is, should a toolchain build be highlighted if the toolchain file matches the build we are testing with or should only the latest such toolchain be highlighted?

**Comment by semorrison** [comment]
The toolchain specified in the project's `lean-toolchain` on its `master`/`main` branch.
